import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../providers";
import { AppClient } from "../components/AppClient";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-slate-200">
          <AppClient />
          <Toaster position="bottom-right" />
          {children}
        </body>
      </Providers>
    </html>
  );
}
